package io.github.pandier.snowball.world

import io.github.pandier.snowball.Snowball
import io.github.pandier.snowball.registry.RegistryReference
import net.kyori.adventure.key.Key

public object GameRules {
    @JvmField public val ADVANCE_TIME: RegistryReference<GameRule<Boolean>> = ref("advance_time")
    @JvmField public val ADVANCE_WEATHER: RegistryReference<GameRule<Boolean>> = ref("advance_weather")
    @JvmField public val ALLOW_ENTERING_NETHER_USING_PORTALS: RegistryReference<GameRule<Boolean>> = ref("allow_entering_nether_using_portals")
    @JvmField public val BLOCK_DROPS: RegistryReference<GameRule<Boolean>> = ref("block_drops")
    @JvmField public val BLOCK_EXPLOSION_DROP_DECAY: RegistryReference<GameRule<Boolean>> = ref("block_explosion_drop_decay")
    @JvmField public val COMMAND_BLOCKS_WORK: RegistryReference<GameRule<Boolean>> = ref("command_blocks_work")
    @JvmField public val COMMAND_BLOCK_OUTPUT: RegistryReference<GameRule<Boolean>> = ref("command_block_output")
    @JvmField public val DROWNING_DAMAGE: RegistryReference<GameRule<Boolean>> = ref("drowning_damage")
    @JvmField public val ELYTRA_MOVEMENT_CHECK: RegistryReference<GameRule<Boolean>> = ref("elytra_movement_check")
    @JvmField public val ENDER_PEARLS_VANISH_ON_DEATH: RegistryReference<GameRule<Boolean>> = ref("ender_pearls_vanish_on_death")
    @JvmField public val ENTITY_DROPS: RegistryReference<GameRule<Boolean>> = ref("entity_drops")
    @JvmField public val FALL_DAMAGE: RegistryReference<GameRule<Boolean>> = ref("fall_damage")
    @JvmField public val FIRE_DAMAGE: RegistryReference<GameRule<Boolean>> = ref("fire_damage")
    @JvmField public val FIRE_SPREAD_RADIUS_AROUND_PLAYER: RegistryReference<GameRule<Int>> = ref("fire_spread_radius_around_player")
    @JvmField public val FORGIVE_DEAD_PLAYERS: RegistryReference<GameRule<Boolean>> = ref("forgive_dead_players")
    @JvmField public val FREEZE_DAMAGE: RegistryReference<GameRule<Boolean>> = ref("freeze_damage")
    @JvmField public val GLOBAL_SOUND_EVENTS: RegistryReference<GameRule<Boolean>> = ref("global_sound_events")
    @JvmField public val IMMEDIATE_RESPAWN: RegistryReference<GameRule<Boolean>> = ref("immediate_respawn")
    @JvmField public val KEEP_INVENTORY: RegistryReference<GameRule<Boolean>> = ref("keep_inventory")
    @JvmField public val LAVA_SOURCE_CONVERSION: RegistryReference<GameRule<Boolean>> = ref("lava_source_conversion")
    @JvmField public val LIMITED_CRAFTING: RegistryReference<GameRule<Boolean>> = ref("limited_crafting")
    @JvmField public val LOCATOR_BAR: RegistryReference<GameRule<Boolean>> = ref("locator_bar")
    @JvmField public val LOG_ADMIN_COMMANDS: RegistryReference<GameRule<Boolean>> = ref("log_admin_commands")
    @JvmField public val MAX_BLOCK_MODIFICATIONS: RegistryReference<GameRule<Int>> = ref("max_block_modifications")
    @JvmField public val MAX_COMMAND_FORKS: RegistryReference<GameRule<Int>> = ref("max_command_forks")
    @JvmField public val MAX_COMMAND_SEQUENCE_LENGTH: RegistryReference<GameRule<Int>> = ref("max_command_sequence_length")
    @JvmField public val MAX_ENTITY_CRAMMING: RegistryReference<GameRule<Int>> = ref("max_entity_cramming")
    @JvmField public val MAX_MINECART_SPEED: RegistryReference<GameRule<Int>> = ref("max_minecart_speed")
    @JvmField public val MAX_SNOW_ACCUMULATION_HEIGHT: RegistryReference<GameRule<Int>> = ref("max_snow_accumulation_height")
    @JvmField public val MOB_DROPS: RegistryReference<GameRule<Boolean>> = ref("mob_drops")
    @JvmField public val MOB_EXPLOSION_DROP_DECAY: RegistryReference<GameRule<Boolean>> = ref("mob_explosion_drop_decay")
    @JvmField public val MOB_GRIEFING: RegistryReference<GameRule<Boolean>> = ref("mob_griefing")
    @JvmField public val NATURAL_HEALTH_REGENERATION: RegistryReference<GameRule<Boolean>> = ref("natural_health_regeneration")
    @JvmField public val PLAYERS_NETHER_PORTAL_CREATIVE_DELAY: RegistryReference<GameRule<Int>> = ref("players_nether_portal_creative_delay")
    @JvmField public val PLAYERS_NETHER_PORTAL_DEFAULT_DELAY: RegistryReference<GameRule<Int>> = ref("players_nether_portal_default_delay")
    @JvmField public val PLAYERS_SLEEPING_PERCENTAGE: RegistryReference<GameRule<Int>> = ref("players_sleeping_percentage")
    @JvmField public val PLAYER_MOVEMENT_CHECK: RegistryReference<GameRule<Boolean>> = ref("player_movement_check")
    @JvmField public val PROJECTILES_CAN_BREAK_BLOCKS: RegistryReference<GameRule<Boolean>> = ref("projectiles_can_break_blocks")
    @JvmField public val PVP: RegistryReference<GameRule<Boolean>> = ref("pvp")
    @JvmField public val RAIDS: RegistryReference<GameRule<Boolean>> = ref("raids")
    @JvmField public val RANDOM_TICK_SPEED: RegistryReference<GameRule<Int>> = ref("random_tick_speed")
    @JvmField public val REDUCED_DEBUG_INFO: RegistryReference<GameRule<Boolean>> = ref("reduced_debug_info")
    @JvmField public val RESPAWN_RADIUS: RegistryReference<GameRule<Int>> = ref("respawn_radius")
    @JvmField public val SEND_COMMAND_FEEDBACK: RegistryReference<GameRule<Boolean>> = ref("send_command_feedback")
    @JvmField public val SHOW_ADVANCEMENT_MESSAGES: RegistryReference<GameRule<Boolean>> = ref("show_advancement_messages")
    @JvmField public val SHOW_DEATH_MESSAGES: RegistryReference<GameRule<Boolean>> = ref("show_death_messages")
    @JvmField public val SPAWNER_BLOCKS_WORK: RegistryReference<GameRule<Boolean>> = ref("spawner_blocks_work")
    @JvmField public val SPAWN_MOBS: RegistryReference<GameRule<Boolean>> = ref("spawn_mobs")
    @JvmField public val SPAWN_MONSTERS: RegistryReference<GameRule<Boolean>> = ref("spawn_monsters")
    @JvmField public val SPAWN_PATROLS: RegistryReference<GameRule<Boolean>> = ref("spawn_patrols")
    @JvmField public val SPAWN_PHANTOMS: RegistryReference<GameRule<Boolean>> = ref("spawn_phantoms")
    @JvmField public val SPAWN_WANDERING_TRADERS: RegistryReference<GameRule<Boolean>> = ref("spawn_wandering_traders")
    @JvmField public val SPAWN_WARDENS: RegistryReference<GameRule<Boolean>> = ref("spawn_wardens")
    @JvmField public val SPECTATORS_GENERATE_CHUNKS: RegistryReference<GameRule<Boolean>> = ref("spectators_generate_chunks")
    @JvmField public val SPREAD_VINES: RegistryReference<GameRule<Boolean>> = ref("spread_vines")
    @JvmField public val TNT_EXPLODES: RegistryReference<GameRule<Boolean>> = ref("tnt_explodes")
    @JvmField public val TNT_EXPLOSION_DROP_DECAY: RegistryReference<GameRule<Boolean>> = ref("tnt_explosion_drop_decay")
    @JvmField public val UNIVERSAL_ANGER: RegistryReference<GameRule<Boolean>> = ref("universal_anger")
    @JvmField public val WATER_SOURCE_CONVERSION: RegistryReference<GameRule<Boolean>> = ref("water_source_conversion")

    private inline fun <reified T : Any> ref(id: String): RegistryReference<GameRule<T>> = Snowball.registries.gameRule(Key.key(Key.MINECRAFT_NAMESPACE, id), T::class.java)
}
