package io.github.pandier.snowball.item

import io.github.pandier.snowball.Snowball
import io.github.pandier.snowball.util.Color
import net.kyori.adventure.key.Key
import net.kyori.adventure.text.Component

public object ItemComponentTypes {
    @JvmField public val CUSTOM_DATA: ItemComponentType<*> = refUnknown("custom_data")
    @JvmField public val MAX_STACK_SIZE: ItemComponentType<Int> = ref("max_stack_size")
    @JvmField public val MAX_DAMAGE: ItemComponentType<Int> = ref("max_damage")
    @JvmField public val DAMAGE: ItemComponentType<Int> = ref("damage")
    @JvmField public val UNBREAKABLE: ItemComponentType<Unit> = ref("unbreakable")
    @JvmField public val CUSTOM_NAME: ItemComponentType<Component> = ref("custom_name")
    @JvmField public val ITEM_NAME: ItemComponentType<Component> = ref("item_name")
    @JvmField public val ITEM_MODEL: ItemComponentType<Key> = ref("item_model")
    @JvmField public val LORE: ItemComponentType<Component> = ref("lore")
    @JvmField public val RARITY: ItemComponentType<ItemRarity> = ref("rarity")
    @JvmField public val ENCHANTMENTS: ItemComponentType<*> = refUnknown("enchantments")
    @JvmField public val CAN_PLACE_ON: ItemComponentType<*> = refUnknown("can_place_on")
    @JvmField public val CAN_BREAK: ItemComponentType<*> = refUnknown("can_break")
    @JvmField public val ATTRIBUTE_MODIFIERS: ItemComponentType<*> = refUnknown("attribute_modifiers")
    @JvmField public val CUSTOM_MODEL_DATA: ItemComponentType<*> = refUnknown("custom_model_data")
    @JvmField public val TOOLTIP_DISPLAY: ItemComponentType<*> = refUnknown("tooltip_display")
    @JvmField public val REPAIR_COST: ItemComponentType<Int> = ref("repair_cost")
    @JvmField public val CREATIVE_SLOT_LOCK: ItemComponentType<Unit> = ref("creative_slot_lock")
    @JvmField public val ENCHANTMENT_GLINT_OVERRIDE: ItemComponentType<Boolean> = ref("enchantment_glint_override")
    @JvmField public val INTANGIBLE_PROJECTILE: ItemComponentType<Unit> = ref("intangible_projectile")
    @JvmField public val FOOD: ItemComponentType<*> = refUnknown("food")
    @JvmField public val CONSUMABLE: ItemComponentType<*> = refUnknown("consumable")
    @JvmField public val USE_REMAINDER: ItemComponentType<*> = refUnknown("use_remainder")
    @JvmField public val USE_COOLDOWN: ItemComponentType<*> = refUnknown("use_cooldown")
    @JvmField public val DAMAGE_RESISTANT: ItemComponentType<*> = refUnknown("damage_resistant")
    @JvmField public val TOOL: ItemComponentType<*> = refUnknown("tool")
    @JvmField public val WEAPON: ItemComponentType<*> = refUnknown("weapon")
    @JvmField public val ENCHANTABLE: ItemComponentType<*> = refUnknown("enchantable")
    @JvmField public val EQUIPPABLE: ItemComponentType<*> = refUnknown("equippable")
    @JvmField public val REPAIRABLE: ItemComponentType<*> = refUnknown("repairable")
    @JvmField public val GLIDER: ItemComponentType<Unit> = ref("glider")
    @JvmField public val TOOLTIP_STYLE: ItemComponentType<Key> = ref("tooltip_style")
    @JvmField public val DEATH_PROTECTION: ItemComponentType<*> = refUnknown("death_protection")
    @JvmField public val BLOCKS_ATTACKS: ItemComponentType<*> = refUnknown("blocks_attacks")
    @JvmField public val STORED_ENCHANTMENTS: ItemComponentType<*> = refUnknown("stored_enchantments")
    @JvmField public val DYED_COLOR: ItemComponentType<Color> = ref("dyed_color")
    @JvmField public val MAP_COLOR: ItemComponentType<Color> = ref("map_color")
    @JvmField public val MAP_ID: ItemComponentType<Int> = ref("map_id")
    @JvmField public val MAP_DECORATIONS: ItemComponentType<*> = refUnknown("map_decorations")
    @JvmField public val MAP_POST_PROCESSING: ItemComponentType<*> = refUnknown("map_post_processing")
    @JvmField public val CHARGED_PROJECTILES: ItemComponentType<*> = refUnknown("charged_projectiles")
    @JvmField public val BUNDLE_CONTENTS: ItemComponentType<*> = refUnknown("bundle_contents")
    @JvmField public val POTION_CONTENTS: ItemComponentType<*> = refUnknown("potion_contents")
    @JvmField public val POTION_DURATION_SCALE: ItemComponentType<Float> = ref("potion_duration_scale")
    @JvmField public val SUSPICIOUS_STEW_EFFECTS: ItemComponentType<*> = refUnknown("suspicious_stew_effects")
    @JvmField public val WRITABLE_BOOK_CONTENT: ItemComponentType<String> = ref("writable_book_content")
    @JvmField public val WRITTEN_BOOK_CONTENT: ItemComponentType<*> = refUnknown("written_book_content")
    @JvmField public val TRIM: ItemComponentType<*> = refUnknown("trim")
    @JvmField public val DEBUG_STICK_STATE: ItemComponentType<*> = refUnknown("debug_stick_state")
    @JvmField public val ENTITY_DATA: ItemComponentType<*> = refUnknown("entity_data")
    @JvmField public val BUCKET_ENTITY_DATA: ItemComponentType<*> = refUnknown("bucket_entity_data")
    @JvmField public val BLOCK_ENTITY_DATA: ItemComponentType<*> = refUnknown("block_entity_data")
    @JvmField public val INSTRUMENT: ItemComponentType<*> = refUnknown("instrument")
    @JvmField public val PROVIDES_TRIM_MATERIAL: ItemComponentType<*> = refUnknown("provides_trim_material")
    @JvmField public val OMINOUS_BOTTLE_AMPLIFIER: ItemComponentType<Int> = ref("ominous_bottle_amplifier")
    @JvmField public val JUKEBOX_PLAYABLE: ItemComponentType<*> = refUnknown("jukebox_playable")
    @JvmField public val PROVIDES_BANNER_PATTERNS: ItemComponentType<*> = refUnknown("provides_banner_patterns")
    @JvmField public val RECIPES: ItemComponentType<*> = refUnknown("recipes")
    @JvmField public val LODESTONE_TRACKER: ItemComponentType<*> = refUnknown("lodestone_tracker")
    @JvmField public val FIREWORK_EXPLOSION: ItemComponentType<*> = refUnknown("firework_explosion")
    @JvmField public val FIREWORKS: ItemComponentType<*> = refUnknown("fireworks")
    @JvmField public val PROFILE: ItemComponentType<*> = refUnknown("profile")
    @JvmField public val NOTE_BLOCK_SOUND: ItemComponentType<Key> = ref("note_block_sound")
    @JvmField public val BANNER_PATTERNS: ItemComponentType<*> = refUnknown("banner_patterns")
    @JvmField public val BASE_COLOR: ItemComponentType<*> = refUnknown("base_color")
    @JvmField public val POT_DECORATIONS: ItemComponentType<*> = refUnknown("pot_decorations")
    @JvmField public val CONTAINER: ItemComponentType<*> = refUnknown("container")
    @JvmField public val BLOCK_STATE: ItemComponentType<String> = ref("block_state")
    @JvmField public val BEES: ItemComponentType<*> = refUnknown("bees")
    @JvmField public val LOCK: ItemComponentType<*> = refUnknown("lock")
    @JvmField public val CONTAINER_LOOT: ItemComponentType<*> = refUnknown("container_loot")
    @JvmField public val BREAK_SOUND: ItemComponentType<*> = refUnknown("break_sound")
    @JvmField public val VILLAGER_VARIANT: ItemComponentType<*> = refUnknown("villager/variant")
    @JvmField public val WOLF_VARIANT: ItemComponentType<*> = refUnknown("wolf/variant")
    @JvmField public val WOLF_SOUND_VARIANT: ItemComponentType<*> = refUnknown("wolf/sound_variant")
    @JvmField public val WOLF_COLLAR: ItemComponentType<*> = refUnknown("wolf/collar")
    @JvmField public val FOX_VARIANT: ItemComponentType<*> = refUnknown("fox/variant")
    @JvmField public val SALMON_SIZE: ItemComponentType<*> = refUnknown("salmon/size")
    @JvmField public val PARROT_VARIANT: ItemComponentType<*> = refUnknown("parrot/variant")
    @JvmField public val TROPICAL_FISH_PATTERN: ItemComponentType<*> = refUnknown("tropical_fish/pattern")
    @JvmField public val TROPICAL_FISH_BASE_COLOR: ItemComponentType<*> = refUnknown("tropical_fish/base_color")
    @JvmField public val TROPICAL_FISH_PATTERN_COLOR: ItemComponentType<*> = refUnknown("tropical_fish/pattern_color")
    @JvmField public val MOOSHROOM_VARIANT: ItemComponentType<*> = refUnknown("mooshroom/variant")
    @JvmField public val RABBIT_VARIANT: ItemComponentType<*> = refUnknown("rabbit/variant")
    @JvmField public val PIG_VARIANT: ItemComponentType<*> = refUnknown("pig/variant")
    @JvmField public val COW_VARIANT: ItemComponentType<*> = refUnknown("cow/variant")
    @JvmField public val CHICKEN_VARIANT: ItemComponentType<*> = refUnknown("chicken/variant")
    @JvmField public val FROG_VARIANT: ItemComponentType<*> = refUnknown("frog/variant")
    @JvmField public val HORSE_VARIANT: ItemComponentType<*> = refUnknown("horse/variant")
    @JvmField public val PAINTING_VARIANT: ItemComponentType<*> = refUnknown("painting/variant")
    @JvmField public val LLAMA_VARIANT: ItemComponentType<*> = refUnknown("llama/variant")
    @JvmField public val AXOLOTL_VARIANT: ItemComponentType<*> = refUnknown("axolotl/variant")
    @JvmField public val CAT_VARIANT: ItemComponentType<*> = refUnknown("cat/variant")
    @JvmField public val CAT_COLLAR: ItemComponentType<*> = refUnknown("cat/collar")
    @JvmField public val SHEEP_COLOR: ItemComponentType<*> = refUnknown("sheep/color")
    @JvmField public val SHULKER_COLOR: ItemComponentType<*> = refUnknown("shulker/color")

    private inline fun <reified T> ref(id: String): ItemComponentType<T> {
        return Snowball.registries.itemComponentType(Key.key(Key.MINECRAFT_NAMESPACE, id), T::class.java)
    }

    private fun refUnknown(id: String): ItemComponentType<*> {
        return Snowball.registries.itemComponentType(Key.key(Key.MINECRAFT_NAMESPACE, id))
    }
}