package io.github.pandier.snowball.item

import io.github.pandier.snowball.Snowball
import io.github.pandier.snowball.util.Color
import net.kyori.adventure.key.Key
import net.kyori.adventure.text.Component

public object ItemComponentTypes {
    @JvmField public val CUSTOM_DATA: ItemComponentType<*> = ref<Unit>("custom_data")
    @JvmField public val MAX_STACK_SIZE: ItemComponentType<Int> = ref("max_stack_size")
    @JvmField public val MAX_DAMAGE: ItemComponentType<Int> = ref("max_damage")
    @JvmField public val DAMAGE: ItemComponentType<Int> = ref("damage")
    @JvmField public val UNBREAKABLE: ItemComponentType<Unit> = ref("unbreakable")
    @JvmField public val CUSTOM_NAME: ItemComponentType<Component> = ref("custom_name")
    @JvmField public val ITEM_NAME: ItemComponentType<Component> = ref("item_name")
    @JvmField public val ITEM_MODEL: ItemComponentType<Key> = ref("item_model")
    @JvmField public val LORE: ItemComponentType<Component> = ref("lore")
    @JvmField public val RARITY: ItemComponentType<ItemRarity> = ref("rarity")
    @JvmField public val ENCHANTMENTS: ItemComponentType<*> = ref<Unit>("enchantments")
    @JvmField public val CAN_PLACE_ON: ItemComponentType<*> = ref<Unit>("can_place_on")
    @JvmField public val CAN_BREAK: ItemComponentType<*> = ref<Unit>("can_break")
    @JvmField public val ATTRIBUTE_MODIFIERS: ItemComponentType<*> = ref<Unit>("attribute_modifiers")
    @JvmField public val CUSTOM_MODEL_DATA: ItemComponentType<*> = ref<Unit>("custom_model_data")
    @JvmField public val TOOLTIP_DISPLAY: ItemComponentType<*> = ref<Unit>("tooltip_display")
    @JvmField public val REPAIR_COST: ItemComponentType<Int> = ref("repair_cost")
    @JvmField public val CREATIVE_SLOT_LOCK: ItemComponentType<Unit> = ref("creative_slot_lock")
    @JvmField public val ENCHANTMENT_GLINT_OVERRIDE: ItemComponentType<Boolean> = ref("enchantment_glint_override")
    @JvmField public val INTANGIBLE_PROJECTILE: ItemComponentType<Unit> = ref("intangible_projectile")
    @JvmField public val FOOD: ItemComponentType<*> = ref<Unit>("food")
    @JvmField public val CONSUMABLE: ItemComponentType<*> = ref<Unit>("consumable")
    @JvmField public val USE_REMAINDER: ItemComponentType<*> = ref<Unit>("use_remainder")
    @JvmField public val USE_COOLDOWN: ItemComponentType<*> = ref<Unit>("use_cooldown")
    @JvmField public val DAMAGE_RESISTANT: ItemComponentType<*> = ref<Unit>("damage_resistant")
    @JvmField public val TOOL: ItemComponentType<*> = ref<Unit>("tool")
    @JvmField public val WEAPON: ItemComponentType<*> = ref<Unit>("weapon")
    @JvmField public val ENCHANTABLE: ItemComponentType<*> = ref<Unit>("enchantable")
    @JvmField public val EQUIPPABLE: ItemComponentType<*> = ref<Unit>("equippable")
    @JvmField public val REPAIRABLE: ItemComponentType<*> = ref<Unit>("repairable")
    @JvmField public val GLIDER: ItemComponentType<Unit> = ref("glider")
    @JvmField public val TOOLTIP_STYLE: ItemComponentType<Key> = ref("tooltip_style")
    @JvmField public val DEATH_PROTECTION: ItemComponentType<*> = ref<Unit>("death_protection")
    @JvmField public val BLOCKS_ATTACKS: ItemComponentType<*> = ref<Unit>("blocks_attacks")
    @JvmField public val STORED_ENCHANTMENTS: ItemComponentType<*> = ref<Unit>("stored_enchantments")
    @JvmField public val DYED_COLOR: ItemComponentType<Color> = ref("dyed_color")
    @JvmField public val MAP_COLOR: ItemComponentType<Color> = ref("map_color")
    @JvmField public val MAP_ID: ItemComponentType<Int> = ref("map_id")
    @JvmField public val MAP_DECORATIONS: ItemComponentType<*> = ref<Unit>("map_decorations")
    @JvmField public val MAP_POST_PROCESSING: ItemComponentType<*> = ref<Unit>("map_post_processing")
    @JvmField public val CHARGED_PROJECTILES: ItemComponentType<*> = ref<Unit>("charged_projectiles")
    @JvmField public val BUNDLE_CONTENTS: ItemComponentType<*> = ref<Unit>("bundle_contents")
    @JvmField public val POTION_CONTENTS: ItemComponentType<*> = ref<Unit>("potion_contents")
    @JvmField public val POTION_DURATION_SCALE: ItemComponentType<Float> = ref("potion_duration_scale")
    @JvmField public val SUSPICIOUS_STEW_EFFECTS: ItemComponentType<*> = ref<Unit>("suspicious_stew_effects")
    @JvmField public val WRITABLE_BOOK_CONTENT: ItemComponentType<String> = ref("writable_book_content")
    @JvmField public val WRITTEN_BOOK_CONTENT: ItemComponentType<*> = ref<Unit>("written_book_content")
    @JvmField public val TRIM: ItemComponentType<*> = ref<Unit>("trim")
    @JvmField public val DEBUG_STICK_STATE: ItemComponentType<*> = ref<Unit>("debug_stick_state")
    @JvmField public val ENTITY_DATA: ItemComponentType<*> = ref<Unit>("entity_data")
    @JvmField public val BUCKET_ENTITY_DATA: ItemComponentType<*> = ref<Unit>("bucket_entity_data")
    @JvmField public val BLOCK_ENTITY_DATA: ItemComponentType<*> = ref<Unit>("block_entity_data")
    @JvmField public val INSTRUMENT: ItemComponentType<*> = ref<Unit>("instrument")
    @JvmField public val PROVIDES_TRIM_MATERIAL: ItemComponentType<*> = ref<Unit>("provides_trim_material")
    @JvmField public val OMINOUS_BOTTLE_AMPLIFIER: ItemComponentType<Int> = ref("ominous_bottle_amplifier")
    @JvmField public val JUKEBOX_PLAYABLE: ItemComponentType<*> = ref<Unit>("jukebox_playable")
    @JvmField public val PROVIDES_BANNER_PATTERNS: ItemComponentType<*> = ref<Unit>("provides_banner_patterns")
    @JvmField public val RECIPES: ItemComponentType<*> = ref<Unit>("recipes")
    @JvmField public val LODESTONE_TRACKER: ItemComponentType<*> = ref<Unit>("lodestone_tracker")
    @JvmField public val FIREWORK_EXPLOSION: ItemComponentType<*> = ref<Unit>("firework_explosion")
    @JvmField public val FIREWORKS: ItemComponentType<*> = ref<Unit>("fireworks")
    @JvmField public val PROFILE: ItemComponentType<*> = ref<Unit>("profile")
    @JvmField public val NOTE_BLOCK_SOUND: ItemComponentType<Key> = ref("note_block_sound")
    @JvmField public val BANNER_PATTERNS: ItemComponentType<*> = ref<Unit>("banner_patterns")
    @JvmField public val BASE_COLOR: ItemComponentType<*> = ref<Unit>("base_color")
    @JvmField public val POT_DECORATIONS: ItemComponentType<*> = ref<Unit>("pot_decorations")
    @JvmField public val CONTAINER: ItemComponentType<*> = ref<Unit>("container")
    @JvmField public val BLOCK_STATE: ItemComponentType<String> = ref("block_state")
    @JvmField public val BEES: ItemComponentType<*> = ref<Unit>("bees")
    @JvmField public val LOCK: ItemComponentType<*> = ref<Unit>("lock")
    @JvmField public val CONTAINER_LOOT: ItemComponentType<*> = ref<Unit>("container_loot")
    @JvmField public val BREAK_SOUND: ItemComponentType<*> = ref<Unit>("break_sound")
    @JvmField public val VILLAGER_VARIANT: ItemComponentType<*> = ref<Unit>("villager/variant")
    @JvmField public val WOLF_VARIANT: ItemComponentType<*> = ref<Unit>("wolf/variant")
    @JvmField public val WOLF_SOUND_VARIANT: ItemComponentType<*> = ref<Unit>("wolf/sound_variant")
    @JvmField public val WOLF_COLLAR: ItemComponentType<*> = ref<Unit>("wolf/collar")
    @JvmField public val FOX_VARIANT: ItemComponentType<*> = ref<Unit>("fox/variant")
    @JvmField public val SALMON_SIZE: ItemComponentType<*> = ref<Unit>("salmon/size")
    @JvmField public val PARROT_VARIANT: ItemComponentType<*> = ref<Unit>("parrot/variant")
    @JvmField public val TROPICAL_FISH_PATTERN: ItemComponentType<*> = ref<Unit>("tropical_fish/pattern")
    @JvmField public val TROPICAL_FISH_BASE_COLOR: ItemComponentType<*> = ref<Unit>("tropical_fish/base_color")
    @JvmField public val TROPICAL_FISH_PATTERN_COLOR: ItemComponentType<*> = ref<Unit>("tropical_fish/pattern_color")
    @JvmField public val MOOSHROOM_VARIANT: ItemComponentType<*> = ref<Unit>("mooshroom/variant")
    @JvmField public val RABBIT_VARIANT: ItemComponentType<*> = ref<Unit>("rabbit/variant")
    @JvmField public val PIG_VARIANT: ItemComponentType<*> = ref<Unit>("pig/variant")
    @JvmField public val COW_VARIANT: ItemComponentType<*> = ref<Unit>("cow/variant")
    @JvmField public val CHICKEN_VARIANT: ItemComponentType<*> = ref<Unit>("chicken/variant")
    @JvmField public val FROG_VARIANT: ItemComponentType<*> = ref<Unit>("frog/variant")
    @JvmField public val HORSE_VARIANT: ItemComponentType<*> = ref<Unit>("horse/variant")
    @JvmField public val PAINTING_VARIANT: ItemComponentType<*> = ref<Unit>("painting/variant")
    @JvmField public val LLAMA_VARIANT: ItemComponentType<*> = ref<Unit>("llama/variant")
    @JvmField public val AXOLOTL_VARIANT: ItemComponentType<*> = ref<Unit>("axolotl/variant")
    @JvmField public val CAT_VARIANT: ItemComponentType<*> = ref<Unit>("cat/variant")
    @JvmField public val CAT_COLLAR: ItemComponentType<*> = ref<Unit>("cat/collar")
    @JvmField public val SHEEP_COLOR: ItemComponentType<*> = ref<Unit>("sheep/color")
    @JvmField public val SHULKER_COLOR: ItemComponentType<*> = ref<Unit>("shulker/color")

    private fun <T> ref(id: String): ItemComponentType<T> {
        return Snowball.registries.itemComponentType<T>(Key.key(Key.MINECRAFT_NAMESPACE, id))
    }
}