package io.github.pandier.snowball.scoreboard

import io.github.pandier.snowball.Snowball
import java.util.function.Supplier

public object Criteria {
    @JvmField public val DUMMY: Supplier<Criterion> = ref("dummy")
    @JvmField public val TRIGGER: Supplier<Criterion> = ref("trigger")
    @JvmField public val DEATH_COUNT: Supplier<Criterion> = ref("deathCount")
    @JvmField public val PLAYER_KILL_COUNT: Supplier<Criterion> = ref("playerKillCount")
    @JvmField public val TOTAL_KILL_COUNT: Supplier<Criterion> = ref("totalKillCount")
    @JvmField public val HEALTH: Supplier<Criterion> = ref("health")
    @JvmField public val FOOD: Supplier<Criterion> = ref("food")
    @JvmField public val AIR: Supplier<Criterion> = ref("air")
    @JvmField public val ARMOR: Supplier<Criterion> = ref("armor")
    @JvmField public val XP: Supplier<Criterion> = ref("xp")
    @JvmField public val LEVEL: Supplier<Criterion> = ref("level")
    @JvmField public val TEAM_KILL_BLACK: Supplier<Criterion> = ref("teamkill.black")
    @JvmField public val TEAM_KILL_DARK_BLUE: Supplier<Criterion> = ref("teamkill.dark_blue")
    @JvmField public val TEAM_KILL_DARK_GREEN: Supplier<Criterion> = ref("teamkill.dark_green")
    @JvmField public val TEAM_KILL_DARK_AQUA: Supplier<Criterion> = ref("teamkill.dark_aqua")
    @JvmField public val TEAM_KILL_DARK_RED: Supplier<Criterion> = ref("teamkill.dark_red")
    @JvmField public val TEAM_KILL_DARK_PURPLE: Supplier<Criterion> = ref("teamkill.dark_purple")
    @JvmField public val TEAM_KILL_GOLD: Supplier<Criterion> = ref("teamkill.gold")
    @JvmField public val TEAM_KILL_GRAY: Supplier<Criterion> = ref("teamkill.gray")
    @JvmField public val TEAM_KILL_DARK_GRAY: Supplier<Criterion> = ref("teamkill.dark_gray")
    @JvmField public val TEAM_KILL_BLUE: Supplier<Criterion> = ref("teamkill.blue")
    @JvmField public val TEAM_KILL_GREEN: Supplier<Criterion> = ref("teamkill.green")
    @JvmField public val TEAM_KILL_AQUA: Supplier<Criterion> = ref("teamkill.aqua")
    @JvmField public val TEAM_KILL_RED: Supplier<Criterion> = ref("teamkill.red")
    @JvmField public val TEAM_KILL_LIGHT_PURPLE: Supplier<Criterion> = ref("teamkill.light_purple")
    @JvmField public val TEAM_KILL_YELLOW: Supplier<Criterion> = ref("teamkill.yellow")
    @JvmField public val TEAM_KILL_WHITE: Supplier<Criterion> = ref("teamkill.white")
    @JvmField public val KILLED_BY_TEAM_BLACK: Supplier<Criterion> = ref("killedByTeam.black")
    @JvmField public val KILLED_BY_TEAM_DARK_BLUE: Supplier<Criterion> = ref("killedByTeam.dark_blue")
    @JvmField public val KILLED_BY_TEAM_DARK_GREEN: Supplier<Criterion> = ref("killedByTeam.dark_green")
    @JvmField public val KILLED_BY_TEAM_DARK_AQUA: Supplier<Criterion> = ref("killedByTeam.dark_aqua")
    @JvmField public val KILLED_BY_TEAM_DARK_RED: Supplier<Criterion> = ref("killedByTeam.dark_red")
    @JvmField public val KILLED_BY_TEAM_DARK_PURPLE: Supplier<Criterion> = ref("killedByTeam.dark_purple")
    @JvmField public val KILLED_BY_TEAM_GOLD: Supplier<Criterion> = ref("killedByTeam.gold")
    @JvmField public val KILLED_BY_TEAM_GRAY: Supplier<Criterion> = ref("killedByTeam.gray")
    @JvmField public val KILLED_BY_TEAM_DARK_GRAY: Supplier<Criterion> = ref("killedByTeam.dark_gray")
    @JvmField public val KILLED_BY_TEAM_BLUE: Supplier<Criterion> = ref("killedByTeam.blue")
    @JvmField public val KILLED_BY_TEAM_GREEN: Supplier<Criterion> = ref("killedByTeam.green")
    @JvmField public val KILLED_BY_TEAM_AQUA: Supplier<Criterion> = ref("killedByTeam.aqua")
    @JvmField public val KILLED_BY_TEAM_RED: Supplier<Criterion> = ref("killedByTeam.red")
    @JvmField public val KILLED_BY_TEAM_LIGHT_PURPLE: Supplier<Criterion> = ref("killedByTeam.light_purple")
    @JvmField public val KILLED_BY_TEAM_YELLOW: Supplier<Criterion> = ref("killedByTeam.yellow")
    @JvmField public val KILLED_BY_TEAM_WHITE: Supplier<Criterion> = ref("killedByTeam.white")

    private fun ref(id: String): Supplier<Criterion> = Snowball.registries.criterion(id)
}
