package io.github.pandier.snowball.entity

import io.github.pandier.snowball.Snowball
import io.github.pandier.snowball.registry.RegistryReference
import net.kyori.adventure.key.Key
import io.github.pandier.snowball.entity.player.Player

public object EntityTypes {
    @JvmField public val ACACIA_BOAT: RegistryReference<EntityType<Entity>> = ref("acacia_boat")
    @JvmField public val ACACIA_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("acacia_chest_boat")
    @JvmField public val ALLAY: RegistryReference<EntityType<Mob>> = ref("allay")
    @JvmField public val AREA_EFFECT_CLOUD: RegistryReference<EntityType<Entity>> = ref("area_effect_cloud")
    @JvmField public val ARMADILLO: RegistryReference<EntityType<Mob>> = ref("armadillo")
    @JvmField public val ARMOR_STAND: RegistryReference<EntityType<LivingEntity>> = ref("armor_stand")
    @JvmField public val ARROW: RegistryReference<EntityType<Entity>> = ref("arrow")
    @JvmField public val AXOLOTL: RegistryReference<EntityType<Mob>> = ref("axolotl")
    @JvmField public val BAMBOO_CHEST_RAFT: RegistryReference<EntityType<Entity>> = ref("bamboo_chest_raft")
    @JvmField public val BAMBOO_RAFT: RegistryReference<EntityType<Entity>> = ref("bamboo_raft")
    @JvmField public val BAT: RegistryReference<EntityType<Mob>> = ref("bat")
    @JvmField public val BEE: RegistryReference<EntityType<Mob>> = ref("bee")
    @JvmField public val BIRCH_BOAT: RegistryReference<EntityType<Entity>> = ref("birch_boat")
    @JvmField public val BIRCH_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("birch_chest_boat")
    @JvmField public val BLAZE: RegistryReference<EntityType<Mob>> = ref("blaze")
    @JvmField public val BLOCK_DISPLAY: RegistryReference<EntityType<Entity>> = ref("block_display")
    @JvmField public val BOGGED: RegistryReference<EntityType<Mob>> = ref("bogged")
    @JvmField public val BREEZE: RegistryReference<EntityType<Mob>> = ref("breeze")
    @JvmField public val BREEZE_WIND_CHARGE: RegistryReference<EntityType<Entity>> = ref("breeze_wind_charge")
    @JvmField public val CAMEL: RegistryReference<EntityType<Mob>> = ref("camel")
    @JvmField public val CAMEL_HUSK: RegistryReference<EntityType<Mob>> = ref("camel_husk")
    @JvmField public val CAT: RegistryReference<EntityType<Mob>> = ref("cat")
    @JvmField public val CAVE_SPIDER: RegistryReference<EntityType<Mob>> = ref("cave_spider")
    @JvmField public val CHERRY_BOAT: RegistryReference<EntityType<Entity>> = ref("cherry_boat")
    @JvmField public val CHERRY_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("cherry_chest_boat")
    @JvmField public val CHEST_MINECART: RegistryReference<EntityType<Entity>> = ref("chest_minecart")
    @JvmField public val CHICKEN: RegistryReference<EntityType<Mob>> = ref("chicken")
    @JvmField public val COD: RegistryReference<EntityType<Mob>> = ref("cod")
    @JvmField public val COMMAND_BLOCK_MINECART: RegistryReference<EntityType<Entity>> = ref("command_block_minecart")
    @JvmField public val COPPER_GOLEM: RegistryReference<EntityType<Mob>> = ref("copper_golem")
    @JvmField public val COW: RegistryReference<EntityType<Mob>> = ref("cow")
    @JvmField public val CREAKING: RegistryReference<EntityType<Mob>> = ref("creaking")
    @JvmField public val CREEPER: RegistryReference<EntityType<Mob>> = ref("creeper")
    @JvmField public val DARK_OAK_BOAT: RegistryReference<EntityType<Entity>> = ref("dark_oak_boat")
    @JvmField public val DARK_OAK_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("dark_oak_chest_boat")
    @JvmField public val DOLPHIN: RegistryReference<EntityType<Mob>> = ref("dolphin")
    @JvmField public val DONKEY: RegistryReference<EntityType<Mob>> = ref("donkey")
    @JvmField public val DRAGON_FIREBALL: RegistryReference<EntityType<Entity>> = ref("dragon_fireball")
    @JvmField public val DROWNED: RegistryReference<EntityType<Mob>> = ref("drowned")
    @JvmField public val EGG: RegistryReference<EntityType<Entity>> = ref("egg")
    @JvmField public val ELDER_GUARDIAN: RegistryReference<EntityType<Mob>> = ref("elder_guardian")
    @JvmField public val ENDERMAN: RegistryReference<EntityType<Mob>> = ref("enderman")
    @JvmField public val ENDERMITE: RegistryReference<EntityType<Mob>> = ref("endermite")
    @JvmField public val ENDER_DRAGON: RegistryReference<EntityType<Mob>> = ref("ender_dragon")
    @JvmField public val ENDER_PEARL: RegistryReference<EntityType<Entity>> = ref("ender_pearl")
    @JvmField public val END_CRYSTAL: RegistryReference<EntityType<Entity>> = ref("end_crystal")
    @JvmField public val EVOKER: RegistryReference<EntityType<Mob>> = ref("evoker")
    @JvmField public val EVOKER_FANGS: RegistryReference<EntityType<Entity>> = ref("evoker_fangs")
    @JvmField public val EXPERIENCE_BOTTLE: RegistryReference<EntityType<Entity>> = ref("experience_bottle")
    @JvmField public val EXPERIENCE_ORB: RegistryReference<EntityType<Entity>> = ref("experience_orb")
    @JvmField public val EYE_OF_ENDER: RegistryReference<EntityType<Entity>> = ref("eye_of_ender")
    @JvmField public val FALLING_BLOCK: RegistryReference<EntityType<Entity>> = ref("falling_block")
    @JvmField public val FIREBALL: RegistryReference<EntityType<Entity>> = ref("fireball")
    @JvmField public val FIREWORK_ROCKET: RegistryReference<EntityType<Entity>> = ref("firework_rocket")
    @JvmField public val FISHING_BOBBER: RegistryReference<EntityType<Entity>> = ref("fishing_bobber")
    @JvmField public val FOX: RegistryReference<EntityType<Mob>> = ref("fox")
    @JvmField public val FROG: RegistryReference<EntityType<Mob>> = ref("frog")
    @JvmField public val FURNACE_MINECART: RegistryReference<EntityType<Entity>> = ref("furnace_minecart")
    @JvmField public val GHAST: RegistryReference<EntityType<Mob>> = ref("ghast")
    @JvmField public val GIANT: RegistryReference<EntityType<Mob>> = ref("giant")
    @JvmField public val GLOW_ITEM_FRAME: RegistryReference<EntityType<Entity>> = ref("glow_item_frame")
    @JvmField public val GLOW_SQUID: RegistryReference<EntityType<Mob>> = ref("glow_squid")
    @JvmField public val GOAT: RegistryReference<EntityType<Mob>> = ref("goat")
    @JvmField public val GUARDIAN: RegistryReference<EntityType<Mob>> = ref("guardian")
    @JvmField public val HAPPY_GHAST: RegistryReference<EntityType<Mob>> = ref("happy_ghast")
    @JvmField public val HOGLIN: RegistryReference<EntityType<Mob>> = ref("hoglin")
    @JvmField public val HOPPER_MINECART: RegistryReference<EntityType<Entity>> = ref("hopper_minecart")
    @JvmField public val HORSE: RegistryReference<EntityType<Mob>> = ref("horse")
    @JvmField public val HUSK: RegistryReference<EntityType<Mob>> = ref("husk")
    @JvmField public val ILLUSIONER: RegistryReference<EntityType<Mob>> = ref("illusioner")
    @JvmField public val INTERACTION: RegistryReference<EntityType<Entity>> = ref("interaction")
    @JvmField public val IRON_GOLEM: RegistryReference<EntityType<Mob>> = ref("iron_golem")
    @JvmField public val ITEM: RegistryReference<EntityType<Entity>> = ref("item")
    @JvmField public val ITEM_DISPLAY: RegistryReference<EntityType<Entity>> = ref("item_display")
    @JvmField public val ITEM_FRAME: RegistryReference<EntityType<Entity>> = ref("item_frame")
    @JvmField public val JUNGLE_BOAT: RegistryReference<EntityType<Entity>> = ref("jungle_boat")
    @JvmField public val JUNGLE_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("jungle_chest_boat")
    @JvmField public val LEASH_KNOT: RegistryReference<EntityType<Entity>> = ref("leash_knot")
    @JvmField public val LIGHTNING_BOLT: RegistryReference<EntityType<Entity>> = ref("lightning_bolt")
    @JvmField public val LINGERING_POTION: RegistryReference<EntityType<Entity>> = ref("lingering_potion")
    @JvmField public val LLAMA: RegistryReference<EntityType<Mob>> = ref("llama")
    @JvmField public val LLAMA_SPIT: RegistryReference<EntityType<Entity>> = ref("llama_spit")
    @JvmField public val MAGMA_CUBE: RegistryReference<EntityType<Mob>> = ref("magma_cube")
    @JvmField public val MANGROVE_BOAT: RegistryReference<EntityType<Entity>> = ref("mangrove_boat")
    @JvmField public val MANGROVE_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("mangrove_chest_boat")
    @JvmField public val MANNEQUIN: RegistryReference<EntityType<LivingEntity>> = ref("mannequin")
    @JvmField public val MARKER: RegistryReference<EntityType<Entity>> = ref("marker")
    @JvmField public val MINECART: RegistryReference<EntityType<Entity>> = ref("minecart")
    @JvmField public val MOOSHROOM: RegistryReference<EntityType<Mob>> = ref("mooshroom")
    @JvmField public val MULE: RegistryReference<EntityType<Mob>> = ref("mule")
    @JvmField public val NAUTILUS: RegistryReference<EntityType<Mob>> = ref("nautilus")
    @JvmField public val OAK_BOAT: RegistryReference<EntityType<Entity>> = ref("oak_boat")
    @JvmField public val OAK_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("oak_chest_boat")
    @JvmField public val OCELOT: RegistryReference<EntityType<Mob>> = ref("ocelot")
    @JvmField public val OMINOUS_ITEM_SPAWNER: RegistryReference<EntityType<Entity>> = ref("ominous_item_spawner")
    @JvmField public val PAINTING: RegistryReference<EntityType<Entity>> = ref("painting")
    @JvmField public val PALE_OAK_BOAT: RegistryReference<EntityType<Entity>> = ref("pale_oak_boat")
    @JvmField public val PALE_OAK_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("pale_oak_chest_boat")
    @JvmField public val PANDA: RegistryReference<EntityType<Mob>> = ref("panda")
    @JvmField public val PARCHED: RegistryReference<EntityType<Mob>> = ref("parched")
    @JvmField public val PARROT: RegistryReference<EntityType<Mob>> = ref("parrot")
    @JvmField public val PHANTOM: RegistryReference<EntityType<Mob>> = ref("phantom")
    @JvmField public val PIG: RegistryReference<EntityType<Mob>> = ref("pig")
    @JvmField public val PIGLIN: RegistryReference<EntityType<Mob>> = ref("piglin")
    @JvmField public val PIGLIN_BRUTE: RegistryReference<EntityType<Mob>> = ref("piglin_brute")
    @JvmField public val PILLAGER: RegistryReference<EntityType<Mob>> = ref("pillager")
    @JvmField public val PLAYER: RegistryReference<EntityType<Player>> = ref("player")
    @JvmField public val POLAR_BEAR: RegistryReference<EntityType<Mob>> = ref("polar_bear")
    @JvmField public val PUFFERFISH: RegistryReference<EntityType<Mob>> = ref("pufferfish")
    @JvmField public val RABBIT: RegistryReference<EntityType<Mob>> = ref("rabbit")
    @JvmField public val RAVAGER: RegistryReference<EntityType<Mob>> = ref("ravager")
    @JvmField public val SALMON: RegistryReference<EntityType<Mob>> = ref("salmon")
    @JvmField public val SHEEP: RegistryReference<EntityType<Mob>> = ref("sheep")
    @JvmField public val SHULKER: RegistryReference<EntityType<Mob>> = ref("shulker")
    @JvmField public val SHULKER_BULLET: RegistryReference<EntityType<Entity>> = ref("shulker_bullet")
    @JvmField public val SILVERFISH: RegistryReference<EntityType<Mob>> = ref("silverfish")
    @JvmField public val SKELETON: RegistryReference<EntityType<Mob>> = ref("skeleton")
    @JvmField public val SKELETON_HORSE: RegistryReference<EntityType<Mob>> = ref("skeleton_horse")
    @JvmField public val SLIME: RegistryReference<EntityType<Mob>> = ref("slime")
    @JvmField public val SMALL_FIREBALL: RegistryReference<EntityType<Entity>> = ref("small_fireball")
    @JvmField public val SNIFFER: RegistryReference<EntityType<Mob>> = ref("sniffer")
    @JvmField public val SNOWBALL: RegistryReference<EntityType<Entity>> = ref("snowball")
    @JvmField public val SNOW_GOLEM: RegistryReference<EntityType<Mob>> = ref("snow_golem")
    @JvmField public val SPAWNER_MINECART: RegistryReference<EntityType<Entity>> = ref("spawner_minecart")
    @JvmField public val SPECTRAL_ARROW: RegistryReference<EntityType<Entity>> = ref("spectral_arrow")
    @JvmField public val SPIDER: RegistryReference<EntityType<Mob>> = ref("spider")
    @JvmField public val SPLASH_POTION: RegistryReference<EntityType<Entity>> = ref("splash_potion")
    @JvmField public val SPRUCE_BOAT: RegistryReference<EntityType<Entity>> = ref("spruce_boat")
    @JvmField public val SPRUCE_CHEST_BOAT: RegistryReference<EntityType<Entity>> = ref("spruce_chest_boat")
    @JvmField public val SQUID: RegistryReference<EntityType<Mob>> = ref("squid")
    @JvmField public val STRAY: RegistryReference<EntityType<Mob>> = ref("stray")
    @JvmField public val STRIDER: RegistryReference<EntityType<Mob>> = ref("strider")
    @JvmField public val TADPOLE: RegistryReference<EntityType<Mob>> = ref("tadpole")
    @JvmField public val TEXT_DISPLAY: RegistryReference<EntityType<Entity>> = ref("text_display")
    @JvmField public val TNT: RegistryReference<EntityType<Entity>> = ref("tnt")
    @JvmField public val TNT_MINECART: RegistryReference<EntityType<Entity>> = ref("tnt_minecart")
    @JvmField public val TRADER_LLAMA: RegistryReference<EntityType<Mob>> = ref("trader_llama")
    @JvmField public val TRIDENT: RegistryReference<EntityType<Entity>> = ref("trident")
    @JvmField public val TROPICAL_FISH: RegistryReference<EntityType<Mob>> = ref("tropical_fish")
    @JvmField public val TURTLE: RegistryReference<EntityType<Mob>> = ref("turtle")
    @JvmField public val VEX: RegistryReference<EntityType<Mob>> = ref("vex")
    @JvmField public val VILLAGER: RegistryReference<EntityType<Mob>> = ref("villager")
    @JvmField public val VINDICATOR: RegistryReference<EntityType<Mob>> = ref("vindicator")
    @JvmField public val WANDERING_TRADER: RegistryReference<EntityType<Mob>> = ref("wandering_trader")
    @JvmField public val WARDEN: RegistryReference<EntityType<Mob>> = ref("warden")
    @JvmField public val WIND_CHARGE: RegistryReference<EntityType<Entity>> = ref("wind_charge")
    @JvmField public val WITCH: RegistryReference<EntityType<Mob>> = ref("witch")
    @JvmField public val WITHER: RegistryReference<EntityType<Mob>> = ref("wither")
    @JvmField public val WITHER_SKELETON: RegistryReference<EntityType<Mob>> = ref("wither_skeleton")
    @JvmField public val WITHER_SKULL: RegistryReference<EntityType<Entity>> = ref("wither_skull")
    @JvmField public val WOLF: RegistryReference<EntityType<Mob>> = ref("wolf")
    @JvmField public val ZOGLIN: RegistryReference<EntityType<Mob>> = ref("zoglin")
    @JvmField public val ZOMBIE: RegistryReference<EntityType<Mob>> = ref("zombie")
    @JvmField public val ZOMBIE_HORSE: RegistryReference<EntityType<Mob>> = ref("zombie_horse")
    @JvmField public val ZOMBIE_NAUTILUS: RegistryReference<EntityType<Mob>> = ref("zombie_nautilus")
    @JvmField public val ZOMBIE_VILLAGER: RegistryReference<EntityType<Mob>> = ref("zombie_villager")
    @JvmField public val ZOMBIFIED_PIGLIN: RegistryReference<EntityType<Mob>> = ref("zombified_piglin")

    public fun <T : Entity> ref(entry: EntityType<T>): RegistryReference<EntityType<T>> {
        return Snowball.registries.entityType(entry)
    }

    private fun <T : Entity> ref(id: String): RegistryReference<EntityType<T>> {
        return Snowball.registries.entityType(Key.key(Key.MINECRAFT_NAMESPACE, id))
    }
}
